"""Communication Step Counter for DACA-HMAS evaluation layer.

PAPER INTERPRETATION & RECONSTRUCTION NOTE:
The AutoHMA-LLM paper measures communication efficiency using Communication Steps
and Tokens/Data Size across 4 communication phases (Command Delivery, Task Decomposition,
Agent Collaboration, Feedback). The paper does not formally provide an explicit single-step
equation. Therefore, this metric is a **rigorous workflow reconstruction** mapping completed
logical planner-agent coordination rounds to communication steps.

METRIC COMPARISON NOTE:
- communication_steps: Total communication generated by DACA-HMAS, including
  decentralized coordination, peer consensus, state feedback sync, and runtime adaptation.
- paper_communication_steps: Communication inherited from the AutoHMA-LLM architecture,
  intended only for baseline comparison (global_planning + dispatch).

WHAT CONSTITUTES ONE COMMUNICATION STEP:
- One completed logical planner-agent coordination round (an end-to-end exchange consisting
  of directive dispatch + feedback/acknowledgment cycle).

CATEGORY BREAKDOWN:
- `global_planning`: Command delivery & global task decomposition / coalition planning.
- `dispatch`: Task directive dispatch from Cloud LLM to Device LLMs.
- `local_coordination`: Device LLM domain-level task decomposition / local plan generation.
- `peer_consensus`: Multi-domain peer proposal, review exchange, and consensus finalization.
- `feedback_sync`: Domain state / observation synchronization across coordination nodes.
- `handoff_reallocation`: Dynamic ACDS architecture mode switch handoff & post-switch reallocation.

WHAT DOES NOT COUNT (EXECUTION-LEVEL OPERATIONS):
- Simulator timesteps / environment iterations (`step` / `max_steps`).
- Internal agent movement, kinematic updates, or path waypoint updates.
- Low-level control loops (PID updates, NMPC optimization iterations, Q-learning state updates).
- Collision checking, distance matrix calculations, or physics updates.
- Internal agent computation without planner involvement.
"""

from __future__ import annotations
from typing import Any


class CommunicationStepCounter:
    """Passively counts completed logical planner-agent coordination rounds.

    This counter is purely an evaluation-layer metric tracker and does NOT
    modify any simulation execution, LLM prompts, control loops, or random seeds.
    """

    def __init__(self) -> None:
        self._count: int = 0
        self._breakdown: dict[str, int] = {
            "global_planning": 0,
            "dispatch": 0,
            "local_coordination": 0,
            "peer_consensus": 0,
            "feedback_sync": 0,
            "handoff_reallocation": 0,
        }

    def reset(self) -> None:
        """Reset counter and breakdown to 0 at the beginning of each mission."""
        self._count = 0
        for k in self._breakdown:
            self._breakdown[k] = 0

    def increment(self, category: str = "global_planning", amount: int = 1, reason: str = "") -> None:
        """Increment the communication step count and category breakdown after a completed round.

        Args:
            category: Specific coordination category for explainability & auditability.
            amount: Number of completed logical communication rounds to add (default 1).
            reason: Technical description of the completed planner-agent coordination event.
        """
        if amount > 0:
            self._count += amount
            if category in self._breakdown:
                self._breakdown[category] += amount
            else:
                self._breakdown[category] = amount

    @property
    def value(self) -> int:
        """Return the total communication steps count for the mission."""
        return self._count

    @property
    def paper_value(self) -> int:
        """Return the paper-comparable communication steps count (global_planning + dispatch).

        METRIC COMPARISON NOTE:
        - communication_steps = Total communication generated by DACA-HMAS, including
          decentralized coordination, peer consensus, state feedback sync, and runtime adaptation.
        - paper_communication_steps = Communication inherited from the AutoHMA-LLM architecture,
          intended only for baseline comparison (global_planning + dispatch).
        """
        return self._breakdown.get("global_planning", 0) + self._breakdown.get("dispatch", 0)

    @property
    def breakdown(self) -> dict[str, int]:
        """Return the category breakdown of communication steps for explainability."""
        return dict(self._breakdown)

